"""
run_stage6_demo.py -- Generate all deliverables for the final 3D flythrough.

This script loads a pre-calibrated scene (for demonstration, we will use
the arrays generated by the cross-scene calibration run if they exist, or 
we will quickly mock an array) and exports the full set of products to 
`data/products/`.
"""
import os
import numpy as np
from depthwizard.products.export import generate_all_products
import sys

def main():
    # In a real deployment, this absolute height array comes directly out of 
    # Stage 4 / Stage 5 (Calibration / HTC Refinement).
    # Since we are just testing the exporter here, we will generate a synthetic
    # terrain that resembles a small hill with a building on it.

    H, W = 1000, 1000
    gsd_m = 0.09
    
    print("Generating synthetic calibrated elevation map for demo...")
    y, x = np.ogrid[-H/2:H/2, -W/2:W/2]
    
    # Base terrain: gently sloping hill
    terrain = 200.0 + 10.0 * np.exp(-(x**2 + y**2) / (300**2))
    
    # Add a building (50x50 pixels, 15 meters tall)
    building_mask = (np.abs(x) < 25) & (np.abs(y) < 25)
    dsm = terrain.copy()
    dsm[building_mask] += 15.0
    
    # Add some noise
    dsm += np.random.normal(0, 0.1, dsm.shape)
    
    valid_mask = np.ones((H, W), dtype=bool)
    
    output_dir = "data/products/demo"
    print(f"Exporting Stage 6 products to: {output_dir}")
    
    # In a real scenario, CRS and transform are passed down from Stage 1
    demo_crs = "EPSG:32633"
    demo_transform = (gsd_m, 0.0, 500000.0, 0.0, -gsd_m, 4300000.0)

    products = generate_all_products(
        dsm=dsm.astype(np.float32),
        output_dir=output_dir,
        scene_name="sih26175_demo",
        crs=demo_crs,
        transform=demo_transform,
        gsd_m=gsd_m,
        valid_mask=valid_mask,
        ndsm_kernel=51,
    )
    
    print("\n--- STAGE 6 COMPLETE ---")
    for name, path in products.items():
        print(f"✔ {name.upper()}: {path}")

if __name__ == "__main__":
    main()
